/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	migrationv1alpha1 "sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1"
)

// StorageStateLister helps list StorageStates.
// All objects returned here must be treated as read-only.
type StorageStateLister interface {
	// List lists all StorageStates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*migrationv1alpha1.StorageState, err error)
	// Get retrieves the StorageState from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*migrationv1alpha1.StorageState, error)
	StorageStateListerExpansion
}

// storageStateLister implements the StorageStateLister interface.
type storageStateLister struct {
	listers.ResourceIndexer[*migrationv1alpha1.StorageState]
}

// NewStorageStateLister returns a new StorageStateLister.
func NewStorageStateLister(indexer cache.Indexer) StorageStateLister {
	return &storageStateLister{listers.New[*migrationv1alpha1.StorageState](indexer, migrationv1alpha1.Resource("storagestate"))}
}
