/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	migrationv1alpha1 "sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1"
	scheme "sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/versioned/scheme"
)

// StorageStatesGetter has a method to return a StorageStateInterface.
// A group's client should implement this interface.
type StorageStatesGetter interface {
	StorageStates() StorageStateInterface
}

// StorageStateInterface has methods to work with StorageState resources.
type StorageStateInterface interface {
	Create(ctx context.Context, storageState *migrationv1alpha1.StorageState, opts v1.CreateOptions) (*migrationv1alpha1.StorageState, error)
	Update(ctx context.Context, storageState *migrationv1alpha1.StorageState, opts v1.UpdateOptions) (*migrationv1alpha1.StorageState, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, storageState *migrationv1alpha1.StorageState, opts v1.UpdateOptions) (*migrationv1alpha1.StorageState, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*migrationv1alpha1.StorageState, error)
	List(ctx context.Context, opts v1.ListOptions) (*migrationv1alpha1.StorageStateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *migrationv1alpha1.StorageState, err error)
	StorageStateExpansion
}

// storageStates implements StorageStateInterface
type storageStates struct {
	*gentype.ClientWithList[*migrationv1alpha1.StorageState, *migrationv1alpha1.StorageStateList]
}

// newStorageStates returns a StorageStates
func newStorageStates(c *MigrationV1alpha1Client) *storageStates {
	return &storageStates{
		gentype.NewClientWithList[*migrationv1alpha1.StorageState, *migrationv1alpha1.StorageStateList](
			"storagestates",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *migrationv1alpha1.StorageState { return &migrationv1alpha1.StorageState{} },
			func() *migrationv1alpha1.StorageStateList { return &migrationv1alpha1.StorageStateList{} },
		),
	}
}
